### PR TITLE
feat: update sec section

### PR DESCRIPTION
**Pull request by inghylt**
Added links to threat model manifesto and the OWASP Slack channel. Also refined some other parts of the security text to make it more relevant and easier to read.

### CODE REVIEW

**Review by norling — APPROVED** [review]
I like it :) Good links, and it shortens the overall text, making it easier to read

**Review by jonandernovella — APPROVED** [review]
Great stuff. Nice that you also included the Slack of OWASP

**Review by MalinAhlberg — APPROVED** [review]
Nice! Good to do be reminded to think about safety continuously, not only during design.

**Review by nanjiangshu — APPROVED** [review]
Nice changes with the addition of links and cleaner description.

**Review by jhagberg — APPROVED** [review]
Nice Good additions

**Pull request merged**
